# Generated by Django 6.0.4 on 2026-04-17 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.TextField(blank=True, default='')),
                ('asked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-asked_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('availability', models.CharField(blank=True, default='', max_length=100)),
                ('book_url', models.URLField(blank=True, default='', max_length=1000)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'title'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['genre'], name='books_book_genre_4a7cdf_idx'), models.Index(fields=['rating'], name='books_book_rating_d06a65_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, default='', max_length=50)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('predicted_genre', models.CharField(blank=True, default='', max_length=200)),
                ('key_themes', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('chunk_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='books.book')),
            ],
            options={
                'ordering': ['book', 'chunk_index'],
            },
        ),
    ]
