"""
Management command: python manage.py seed_demo_data
Seeds the database with realistic demo books for development/testing.
"""
import logging
from django.core.management.base import BaseCommand
from books.models import Book, AIInsight
from books.ai_service import generate_all_insights, index_book_for_rag

logger = logging.getLogger(__name__)

DEMO_BOOKS = [
    {"title": "A Light in the Attic", "author": "Shel Silverstein", "rating": 3.0, "num_reviews": 24, "description": "A whimsical collection of poetry and illustrations that delights readers of all ages. Silverstein's wordplay, dark humor, and profound observations about childhood make this a beloved classic. From the attic of imagination to the depths of silliness, these poems tackle everything from chores to dreams.", "genre": "Poetry", "price": "£51.77", "availability": "In stock", "book_url": "https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html", "cover_image_url": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"},
    {"title": "Sharp Objects", "author": "Gillian Flynn", "rating": 4.0, "num_reviews": 42, "description": "A brilliant, dark debut thriller by the author of Gone Girl. Reporter Camille Preaker returns to her small hometown to cover the murders of two young girls. But the biggest threat to figuring out who killed them could be the demons from her own past. Filled with twists, psychologically intense, and utterly compulsive.", "genre": "Mystery", "price": "£47.82", "availability": "In stock", "book_url": "https://books.toscrape.com/catalogue/sharp-objects_997/index.html", "cover_image_url": "https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"},
    {"title": "Sapiens: A Brief History of Humankind", "author": "Yuval Noah Harari", "rating": 5.0, "num_reviews": 1200, "description": "A groundbreaking narrative of humanity's creation and evolution, exploring how biology and history define us and how we can shape our future. Harari asks big questions: What made homo sapiens the dominant species? How did money, empires, and religion emerge? And where are we headed? A fascinating and provocative look at the entire sweep of human history.", "genre": "History", "price": "£54.23", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/23692271-sapiens", "cover_image_url": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"},
    {"title": "The Hunger Games", "author": "Suzanne Collins", "rating": 5.0, "num_reviews": 8765, "description": "In a dystopian future, the nation of Panem consists of a wealthy Capitol and twelve impoverished districts. As punishment for a past rebellion, each district must offer one boy and one girl to compete in the annual Hunger Games — a televised fight to the death. When sixteen-year-old Katniss Everdeen volunteers to take her sister's place, she begins a journey that will challenge everything she knows.", "genre": "Science Fiction", "price": "£14.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/2767052-the-hunger-games", "cover_image_url": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"},
    {"title": "Atomic Habits", "author": "James Clear", "rating": 5.0, "num_reviews": 22000, "description": "No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear reveals practical strategies that will teach you how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. If you're struggling to change your habits, the problem isn't you. It's your system.", "genre": "Self-Help", "price": "£16.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/40121378-atomic-habits", "cover_image_url": "https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "rating": 4.0, "num_reviews": 4530, "description": "Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession with beautiful former lover Daisy Buchanan. A timeless critique of the American Dream, the hollowness of the upper class, and the impossibility of recapturing the past.", "genre": "Classic Fiction", "price": "£9.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/4671.The_Great_Gatsby", "cover_image_url": "https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"},
    {"title": "Dune", "author": "Frank Herbert", "rating": 5.0, "num_reviews": 9800, "description": "Set in the distant future amidst a feudal interstellar society, Dune tells the story of young Paul Atreides whose family accepts stewardship of the desert planet Arrakis — the only source of the most valuable substance in the universe. A tale of politics, religion, ecology, technology, and human emotion, considered the greatest science fiction novel ever written.", "genre": "Science Fiction", "price": "£18.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/44767458-dune", "cover_image_url": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"},
    {"title": "To Kill a Mockingbird", "author": "Harper Lee", "rating": 5.0, "num_reviews": 5210, "description": "A landmark of American literature, this Pulitzer Prize-winning masterpiece follows Scout Finch as her father, lawyer Atticus Finch, defends a Black man falsely accused of rape in the Deep South during the 1930s. Profound in its portrayal of racial injustice, moral growth, and human compassion.", "genre": "Classic Fiction", "price": "£11.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/2657.To_Kill_a_Mockingbird", "cover_image_url": "https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"},
    {"title": "1984", "author": "George Orwell", "rating": 5.0, "num_reviews": 7654, "description": "Orwell's dystopian masterpiece depicts a totalitarian society ruled by Big Brother, where independent thinking is thoughtcrime. Winston Smith secretly hates the Party and dreams of rebellion. The concepts — doublethink, Newspeak, the memory hole — have become part of our cultural vocabulary and remain eerily relevant today.", "genre": "Dystopian Fiction", "price": "£10.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/40961427-1984", "cover_image_url": "https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"},
    {"title": "The Midnight Library", "author": "Matt Haig", "rating": 4.0, "num_reviews": 3800, "description": "Between life and death there is a library. When Nora Seed finds herself in the Midnight Library, she has a chance to make things right. The Midnight Library contains books of every life she could have lived. Each presents the chance to undo a decision and see how things would have panned out. A profound meditation on the infinite possibilities of life.", "genre": "Fiction", "price": "£13.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/52578297-the-midnight-library", "cover_image_url": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"},
    {"title": "Harry Potter and the Philosopher's Stone", "author": "J.K. Rowling", "rating": 5.0, "num_reviews": 18500, "description": "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat. On Harry's eleventh birthday, a great beetle-eyed giant called Rubeus Hagrid bursts in with astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. The beginning of an extraordinary journey.", "genre": "Fantasy", "price": "£15.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/72193", "cover_image_url": "https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"},
    {"title": "The Silent Patient", "author": "Alex Michaelides", "rating": 4.0, "num_reviews": 5100, "description": "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer. One evening her husband Gabriel returns home and Alicia shoots him five times in the face, then never speaks another word. A gripping psychological thriller with a twist you won't see coming.", "genre": "Thriller", "price": "£14.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/40097951", "cover_image_url": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"},
    {"title": "Educated", "author": "Tara Westover", "rating": 5.0, "num_reviews": 6200, "description": "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure she received an education. When her brother got himself into college, Tara decided to try a new kind of life. Her quest for knowledge transformed her.", "genre": "Biography", "price": "£16.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/35133922-educated", "cover_image_url": "https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"},
    {"title": "Dune", "author": "Frank Herbert", "rating": 5.0, "num_reviews": 9800, "description": "Epic science fiction set on the desert planet Arrakis, source of the most valuable substance in the universe — the spice melange. Paul Atreides must navigate political intrigue, religious prophecy, and survival in an unforgiving world. A masterwork of world-building and human drama.", "genre": "Science Fiction", "price": "£18.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/44767458", "cover_image_url": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"},
    {"title": "The Alchemist", "author": "Paulo Coelho", "rating": 4.0, "num_reviews": 11200, "description": "A magical story of Santiago, an Andalusian shepherd boy who journeys from his homeland in Spain to the Egyptian desert in search of a treasure buried near the Pyramids. Along the way, he meets a Gypsy woman, a man who calls himself king, and an alchemist. A fable about following your dream.", "genre": "Fiction", "price": "£12.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/18144590", "cover_image_url": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"},
    {"title": "Thinking, Fast and Slow", "author": "Daniel Kahneman", "rating": 5.0, "num_reviews": 6700, "description": "Nobel Prize winner Daniel Kahneman reveals the two systems that drive the way we think. System 1 is fast, intuitive, and emotional; System 2 is slower and more deliberative. Drawing on decades of research, Kahneman exposes the capabilities and biases of fast thinking and the pervasive influence of intuitive impressions on our behavior.", "genre": "Psychology", "price": "£17.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/11468377", "cover_image_url": "https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"},
    {"title": "The Name of the Wind", "author": "Patrick Rothfuss", "rating": 5.0, "num_reviews": 4300, "description": "Told in Kvothe's own words, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen. From his childhood in a troupe of traveling players, to years spent as a near-feral orphan, to his bid to enter a legendary school of magic. A masterwork of fantasy storytelling.", "genre": "Fantasy", "price": "£19.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/186074", "cover_image_url": "https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"},
    {"title": "The Power of Now", "author": "Eckhart Tolle", "rating": 4.0, "num_reviews": 8900, "description": "A guide to spiritual enlightenment that has sold millions of copies worldwide. Tolle teaches readers to recognize themselves as the eternal self that lies beneath the egoic mind. The key to spiritual illumination is living in the present moment — through personal stories and dialogues, Tolle shows how to find peace and joy right now.", "genre": "Self-Help", "price": "£13.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/6708", "cover_image_url": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"},
    {"title": "The Girl with the Dragon Tattoo", "author": "Stieg Larsson", "rating": 4.0, "num_reviews": 7200, "description": "Harriet Vanger disappeared over forty years ago. Her aged uncle suspects murder within his own family. He hires disgraced journalist Mikael Blomkvist. Together with the tattooed, antisocial hacker Lisbeth Salander, they unearth a dark history of unspeakable crimes in this gripping Scandinavian thriller.", "genre": "Mystery", "price": "£16.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/2429135", "cover_image_url": "https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"},
    {"title": "Becoming", "author": "Michelle Obama", "rating": 5.0, "num_reviews": 9100, "description": "In her memoir, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her — from her childhood on the South Side of Chicago to her years as an executive balancing the demands of motherhood and work, to her time spent at the most famous address in the world. A deeply personal reckoning with a lot of bittersweet moments.", "genre": "Biography", "price": "£18.99", "availability": "In stock", "book_url": "https://www.goodreads.com/book/show/38746485-becoming", "cover_image_url": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"},
]


class Command(BaseCommand):
    help = 'Seeds the database with 20 demo books and indexes them for RAG'

    def add_arguments(self, parser):
        parser.add_argument('--with-ai', action='store_true', help='Generate AI insights via OpenRouter')

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS(f'Seeding {len(DEMO_BOOKS)} demo books...'))
        created = 0
        for data in DEMO_BOOKS:
            book, is_new = Book.objects.update_or_create(title=data['title'], defaults=data)
            if is_new:
                created += 1

            if options['with_ai'] and book.description:
                try:
                    insights = generate_all_insights(book)
                    AIInsight.objects.update_or_create(book=book, defaults=insights)
                    self.stdout.write(f'  AI insights: {book.title[:50]}')
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'  AI failed for {book.title[:40]}: {e}'))

            index_book_for_rag(book)

        self.stdout.write(self.style.SUCCESS(f'Done! {created} new, {len(DEMO_BOOKS) - created} updated.'))
